ARDUINO_DIR = ${HOME}/Arduino
# Répertoire des librairies externes
USER_LIB_PATH = ${ARDUINO_DIR}/libraries
# Répertoire des librairies internes
PROJECT_LIB_PATH = ../libraries
#PROJECT_LIBS = wifi_scan_ap
ARDUINO_LIBS = SoftwareSerial WiFi_Shield-master wifi_scan_ap
OBJDIR = ${HOME}/BaliseBuild
BOARD_TAG = pro.menu.cpu.16MHzatmega328
ARDUINO_PORT = /dev/ttyUSB*
AVRDUDE_OPTS = -q
ISP_PROG = avrispmkII
ISP_PORT = usb
include ../../build/arduino/Arduino.mk
